node_group::config:
# allow the use of a value in another node_group
allow_duplicates: False
# allow referencing other node_groups, will expand and merge values to base type
allow_inception: False

# node_group object definitions go here, example:
# development:
# - "dev-host1"