# example application definition
# 3 parts:
# 1) node_group::dependencies
# 2) package::dependencies
# 3) package::key::overrides

# example of 1)
#node_group::dependencies:
# - "pools::host1"

# example of 2)
#package::dependencies:
# - "example.package"

# example of 3)
#package::key::overrides:
#  "example.package::example.key" :
#    "default" : "overriden_key"